### ISSUE TITLE
Need to update supported version for jest

### ISSUE THREAD

**Issue by uhyunpark** [morganstanley/ts-mocking-bird#81]
Hey there, jest stable version bumped to [29.x](https://jestjs.io/versions) and peer dependencies need an update to support new versions. 

It seems there's already an [example](https://github.com/morganstanley/ts-mocking-bird/pull/72), could you guys help with it? Or can I make a PR somehow?

**Comment by Roaders** [comment]
Just released version 0.7.0 which supports jest 29. Thanks for pointing this out.
